<?php
$a = 5;
$b = 1;
$total = $a + $b + 11;
echo $total;
echo '<br/>';
const _WEB_HOST_ROOT = 'kimcuc.bkhcm@gmail.com';
echo _WEB_HOST_ROOT;
echo '<br/>';
// .=
$outputString = 'Learning english';
$outputString .= ' throught stories';
echo $outputString;
echo '<br/>';
// +, -, *, /, %, **, ++, --
$a = 7;
$b = 10;
$total =$a + $b;
echo $total;
echo '<br/>';
$a = 10;
$b = 20;
$result = $a - $b;
echo $result;
echo '<br/>';
$a = 30;
$b = 3;
$result1 = $a * $b;
echo $result1;
echo '<br/>';
$a = 2;
$b = 3;
$result2 = $a / $b;
echo $result2;
echo '<br/>';
$a = 15;
$b = 10;
$result3 = $a % $b;
echo $result3;
echo '<br/>';
$a = 2;
$b = 3;
$result4 = $a ** $b;
echo $result4;
echo '<br/>';
$count = 0;
$count++; //$count = $count +1;
echo 'scount'.$count.'<br/>';
$count = 1;
$aResult = ++$count;
echo 'aResult'.$aResult.'<br/>';
$aCount = 1;
$aCount--;
echo 'aCount'.$aCount.'<br/>';
// +=, -=, /=, *=, %=
$c = 10;
$c += 1;
echo $c;
echo '<br/>';
$d = 12;
$d -= 2;
echo $d;
echo '<br/>';
$e = 15;
$e *= 2;
echo $e;
echo '<br/>';
$f = 11;
$f /= 3;
echo $f;
echo '<br/>';
$g = 13;
$g %=4;
echo $g;
echo '<br/>';
